# -*- coding: utf-8 -*-
"""Forex_Gold_Corr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XGsXImpwlsTxZcFhNRFcdNAr9rBzdkk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

# Add GC=F (Gold Futures) or GLD (ETF) — both work well
pairs = {
    'EURUSD=X' : 'EUR/USD',
    'GBPUSD=X' : 'GBP/USD',
    'USDJPY=X' : 'USD/JPY',
    'AUDUSD=X' : 'AUD/USD',
    'USDCAD=X' : 'USD/CAD',
    'USDCHF=X' : 'USD/CHF',
    'NZDUSD=X' : 'NZD/USD',
    'GC=F'     : 'Gold'       #  Gold Futures (XAU/USD)
}

# Download data
data = yf.download(list(pairs.keys()), start='2025-01-01', end='2026-01-01')['Close']
data.rename(columns=pairs, inplace=True)

# Calculate returns
returns = data.pct_change().dropna()
corr_matrix = returns.corr()

fig, ax = plt.subplots(figsize=(11, 9))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='RdYlGn',
    vmin=-1, vmax=1,
    linewidths=0.5,
    square=True,
    ax=ax
)

# Highlight the Gold row and column with a border
gold_idx = list(corr_matrix.columns).index('Gold')
for spine in ['top', 'bottom', 'left', 'right']:
    ax.add_patch(plt.Rectangle(
        (gold_idx, 0), 1, len(corr_matrix),       # column highlight
        fill=False, edgecolor='gold', lw=3, clip_on=False
    ))
    ax.add_patch(plt.Rectangle(
        (0, gold_idx), len(corr_matrix), 1,        # row highlight
        fill=False, edgecolor='gold', lw=3, clip_on=False
    ))

plt.title('Forex + Gold Correlation Matrix', fontsize=14)
plt.tight_layout()
plt.show()

# Pairs most theoretically linked to gold
gold_pairs = ['EUR/USD', 'USD/CHF', 'AUD/USD', 'USD/JPY']
colors     = ['steelblue', 'tomato', 'seagreen', 'darkorange']

fig, axes = plt.subplots(len(gold_pairs), 1, figsize=(13, 10), sharex=True)

for ax, pair, color in zip(axes, gold_pairs, colors):
    roll = returns['Gold'].rolling(30).corr(returns[pair])
    ax.plot(roll, color=color, linewidth=1.2, label=f'Gold vs {pair}')
    ax.axhline(0, color='black', linestyle='--', linewidth=0.7)
    ax.fill_between(roll.index, roll, 0,
                    where=(roll > 0), alpha=0.15, color='green')
    ax.fill_between(roll.index, roll, 0,
                    where=(roll < 0), alpha=0.15, color='red')
    ax.set_ylim(-1, 1)
    ax.legend(loc='upper right', fontsize=9)
    ax.set_ylabel('Corr', fontsize=8)

axes[-1].set_xlabel('Date')
fig.suptitle('30-Day Rolling Correlation: Gold vs Forex Pairs', fontsize=13)
plt.tight_layout()
plt.show()

gold_corr = corr_matrix['Gold'].drop('Gold').sort_values(ascending=False)

print("Gold Correlation with Forex Pairs:")
print("=" * 35)
for pair, val in gold_corr.items():
    bar   = '█' * int(abs(val) * 20)
    sign  = '+' if val >= 0 else '-'
    print(f"  {pair:<10} {sign}{abs(val):.3f}  {bar}")

